### ISSUE TITLE
ライセンスの設定

### ISSUE THREAD

**Issue by asashiho** [tsubasaxZZZ/aks-hardway#2]
適切なライセンスを設定していただけるとありがたいです！

**Comment by tsubasaxZZZ** [comment]
Apache 2.0 License を設定しました。何か問題ありましたらご連絡くださいませ。

**Comment by asashiho** [comment]
@tsubasaxZZZ お忙しいところありがとうございます～～～ ❤️  これでパートナー様やお客様にご案内しやすくなりました！随時アップデートしてpull reqさせていただきますので、どうぞよろしくお願いいたします 👍
